ALTER TABLE backtest_runs
    ADD COLUMN IF NOT EXISTS regime_filter_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS regime_filter_period INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS regime_min_atr_percent DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS regime_max_atr_percent DOUBLE PRECISION NOT NULL DEFAULT 0;
