ALTER TABLE backtest_runs
    ADD COLUMN IF NOT EXISTS gross_profit_loss DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_fees DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS estimated_slippage_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS round_trip_cost_percent DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS break_even_move_percent DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE strategy_comparison_results
    ADD COLUMN IF NOT EXISTS gross_profit_loss DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_fees DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS estimated_slippage_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS round_trip_cost_percent DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS break_even_move_percent DOUBLE PRECISION NOT NULL DEFAULT 0;
