ALTER TABLE backtest_runs
    ADD COLUMN buy_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN sell_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN best_trade NUMERIC(30, 12) NOT NULL DEFAULT 0,
    ADD COLUMN worst_trade NUMERIC(30, 12) NOT NULL DEFAULT 0,
    ADD COLUMN average_win NUMERIC(30, 12) NOT NULL DEFAULT 0,
    ADD COLUMN average_loss NUMERIC(30, 12) NOT NULL DEFAULT 0,
    ADD COLUMN open_position BOOLEAN NOT NULL DEFAULT FALSE;
