ALTER TABLE backtest_runs
    ADD COLUMN IF NOT EXISTS expectancy DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS trades_per_day DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS churn_ratio DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sharpe_ratio DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sortino_ratio DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE strategy_comparison_results
    ADD COLUMN IF NOT EXISTS expectancy DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS trades_per_day DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS churn_ratio DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sharpe_ratio DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sortino_ratio DOUBLE PRECISION NOT NULL DEFAULT 0;
